import type { AvailableLanguageTag } from "@/paraglide/runtime";
// file generated by the Paraglide-Next init command
import { Middleware, Navigation, PrefixStrategy } from "@inlang/paraglide-next";

const strategy = PrefixStrategy<AvailableLanguageTag>({ prefixDefault: "never" });

export const middleware = Middleware({ strategy });
export const { Link, useRouter, usePathname, redirect, permanentRedirect } = Navigation({ strategy });
