source ./.env
docker run -p 3000:3000 -e CORS_ALLOW_ORIGINS=$CORS_ALLOW_ORIGINS -e DATABASE_URL=$DATABASE_URL -e FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID -e COOKIE_SIGN_SECRET=$COOKIE_SIGN_SECRET -e CLOUDFLARE_R2_ACCESS_KEY=$CLOUDFLARE_R2_ACCESS_KEY -e CLOUDFLARE_R2_SECRET_KEY=$CLOUDFLARE_R2_SECRET_KEY -e CLOUDFLARE_R2_TOKEN=$CLOUDFLARE_R2_TOKEN ut-bridge
