name: Deploy
on:
  push:
    branches:
      - release

env:
  FLY_PROD_TOKEN: ${{ secrets.FLY_ACCESS_TOKEN }}
jobs:
  deploy:
    name: Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --access-token "$FLY_PROD_TOKEN" --config ./fly/prod.toml
